coverage:
  status:
    project: off
    patch: off
comment: false
flags:
  clusterfuzz:
    # We only report ClusterFuzz coverage nightly
    carryforward: true
  ledgers:
    carryforward: true
  nightly_ledgers:
    carryforward: true
